services:
    front-end:
        container_name: thumbnails
        build: ./_docker/
        ports:
            - 3000:3000
        privileged: true
        volumes:
            - ./_application:/app
            - ./_application/node_modules:/app/node_modules
        tty: true
        stdin_open: true
        command: /bin/bash -c "npm install -g npm@latest && npm update && npm run dev"
