import type { Metadata } from "next";
import "the-new-css-reset/css/reset.css";
import "./globals.scss";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { GlobalProvider } from '@/app/_context/GlobalState';

// my component
import Header from "@/app/_components/header"
import Stepbar from "@/app/_components/stepbar"
import Footer from "@/app/_components/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "サムネ作るやつ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <GlobalProvider>
          <AppRouterCacheProvider>
            <Header/>
            <Stepbar/>
            {children}
            <Footer/>
          </AppRouterCacheProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
