import type { Metadata } from "next";
import "the-new-css-reset/css/reset.css";
import "./globals.scss";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { GlobalStateProvider } from './_context/GlobalState';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "サムネ作るやつ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <GlobalStateProvider>
            {children}
          </GlobalStateProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
